#!/usr/bin/python3
'''
Foot pedal controller.

Written by James Gao
Modified by Anwar Nunez-Elizalde
'''
import serial
import uinput

# emacs: execute py2
# sequence_left = [uinput.KEY_RIGHTALT, uinput.KEY_C, uinput.KEY_RIGHTALT, uinput.KEY_RIGHTSHIFT, uinput.KEY_1]
# TAB windows
# sequence_left = [uinput.KEY_RIGHTALT, uinput.KEY_TAB]
sequence_left = [uinput.KEY_RIGHTALT, uinput.KEY_X, uinput.KEY_RIGHTALT, uinput.KEY_S]
# emacs: execute code for py3
sequence_right = [uinput.KEY_RIGHTALT, uinput.KEY_C, uinput.KEY_RIGHTALT, uinput.KEY_R]
keys = sequence_left + sequence_right
combos = [sequence_left, sequence_right]


print('Started foot controller!')

def main(port="/dev/ttyUSB0"):
    with serial.Serial(port, 230400) as port, uinput.Device(keys) as dev:
        run = True
        while run:
            try:
                state = port.readline().decode()
                lr = 1 if state[1] == 'R' else 0
                is_key_press = int(state[0])
                if not is_key_press:
                    continue
                sequence = combos[lr]
                dev.emit_combo(sequence)

            except KeyboardInterrupt:
                run = False

if __name__ == "__main__":
    main()
